name: Sometech Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'users/**'
  workflow_dispatch:
    inputs:
      build-message:
        description: 'Custom message for the build action'
        required: false
        type: string
        default: 'Build Action One'
      scan-message:
        description: 'Custom message for the scan action'
        required: false
        type: string
        default: 'Scan Action One'
      deploy-message:
        description: 'Custom message for the deploy action'
        required: false
        type: string
        default: 'Deployment Action One'

jobs:
  someAppName:
    uses: ava-client-ussouth-scg-argon/argon-automation/.github/workflows/rw-sometech-build-and-deploy-to-sometarget.yaml@main
    with:
      build-message: ${{ inputs.build-message }}
      scan-message: ${{ inputs.scan-message }}
      deploy-message: ${{ inputs.deploy-message }}
    secrets: inherit