name: Run Java Pipeline

on:
  push:
    branches:
      - main
      - 'users/**'
  workflow_dispatch:
    inputs:
      jdkVersion:
        description: 'What version of Java to use'
        required: true
        type: string
      javaDistribution:
        description: 'Which Java distribution to use'
        required: true
        type: string
      remoteUser:
        description: 'SSH username for the remote server'
        required: true
        type: string
      remotePath:
        description: 'Path on the remote server to deploy artifacts'
        required: true
        type: string
      webAppDirectory:
        description: 'Target directory on the remote server for the web app'
        required: true
        type: string
      artifactJarName:
        description: 'Name of the Java artifact (JAR file) to run'
        required: true
        type: string

jobs:        
  run-pipeline:
    uses: ./.github/workflows/rw-java-build-and-deploy.yaml
    with:
      jdkVersion: ${{ inputs.jdkVersion }}
      javaDistribution: ${{ inputs.javaDistribution }}
      remoteUser: ${{ inputs.remoteUser }}
      remotePath: ${{ inputs.remotePath }}
      webAppDirectory: ${{ inputs.webAppDirectory }}
      artifactJarName: ${{ inputs.artifactJarName }}
    secrets: inherit