name: Build and Deploy SSIS/SSRS

permissions:
  contents: read
  actions: read

on:
  workflow_call:
    inputs:
      remoteUser:
        description: 'SSH username for the remote server'
        required: true
        type: string
      remoteHost:
        description: 'Remote host address'
        required: true
        type: string
      remotePath:
        description: 'Path on the remote server to deploy artifacts'
        required: true
        type: string
      webAppDirectory:
        description: 'Target directory on the remote server for the web app'
        required: true
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Run Build and Scan
        uses: ./composites/ssis-ssrs/build
        with:
          SSC_URL: ${{ secrets.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SC_SAST_CLIENT_AUTH_TOKEN: ${{ secrets.SC_SAST_CLIENT_AUTH_TOKEN }}
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  deploy-to-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Run Deploy Against Dev
        uses: ./composites/ssis-ssrs/deploy
        with:
          sshPrivateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          remoteUser: ${{ inputs.remoteUser }}
          remoteHost: ${{ secrets.REMOTE_HOST }}
          remotePath: ${{ inputs.remotePath }}
          webAppDirectory: ${{ inputs.webAppDirectory }}

  deploy-to-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Run Deploy Against Test
        uses: ./composites/ssis-ssrs/deploy
        with:
          sshPrivateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          remoteUser: ${{ inputs.remoteUser }}
          remoteHost: ${{ secrets.REMOTE_HOST }}
          remotePath: ${{ inputs.remotePath }}
          webAppDirectory: ${{ inputs.webAppDirectory }}

  deploy-to-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-to-test
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Run Deploy Against Prod
        uses: ./composites/ssis-ssrs/deploy
        with:
          sshPrivateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          remoteUser: ${{ inputs.remoteUser }}
          remoteHost: ${{ secrets.REMOTE_HOST }}
          remotePath: ${{ inputs.remotePath }}
          webAppDirectory: ${{ inputs.webAppDirectory }}